-- Liquidación de recaudos al proveedor/cliente (fk_usuario_solicitud).
-- Ejecutar después de 23-pedido-tarifa-envio.sql.

CREATE TABLE IF NOT EXISTS public.cliente_liquidacion_config (
  fk_usuario integer PRIMARY KEY REFERENCES public.usuarios (id_usuario),
  frecuencia_dias integer NOT NULL DEFAULT 15,
  fk_metodo_devolucion integer NULL REFERENCES public.metodo_pago (id_metodo_pago),
  referencia_devolucion text NULL,
  actualizado_en timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.cliente_liquidacion_config IS
  'Acuerdo comercial por cliente: cada cuántos días liquidar recaudos y medio de devolución.';

CREATE TABLE IF NOT EXISTS public.liquidacion_lote (
  id_liquidacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_usuario_cliente integer NOT NULL REFERENCES public.usuarios (id_usuario),
  recaudo_total numeric(14, 4) NOT NULL,
  tarifa_descontada numeric(14, 4) NOT NULL,
  monto_neto numeric(14, 4) NOT NULL,
  pedidos_total integer NOT NULL,
  fk_metodo_devolucion integer NULL REFERENCES public.metodo_pago (id_metodo_pago),
  referencia_pago text NULL,
  fecha_desde date NOT NULL,
  fecha_hasta date NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.liquidacion_detalle (
  id_liquidacion integer NOT NULL REFERENCES public.liquidacion_lote (id_liquidacion) ON DELETE CASCADE,
  fk_pedido integer NOT NULL UNIQUE REFERENCES public.pedidos (id_pedido),
  valor_recaudado numeric(14, 4) NOT NULL,
  tarifa_envio numeric(14, 4) NOT NULL,
  monto_neto numeric(14, 4) NOT NULL,
  PRIMARY KEY (id_liquidacion, fk_pedido)
);

CREATE INDEX IF NOT EXISTS idx_liquidacion_lote_cliente
  ON public.liquidacion_lote (fk_usuario_cliente, creado_en DESC);
