-- Recrear `usuarios` con id entero + auth_user_id (tablas vacías / sin datos que conservar).
-- Ejecutar en Supabase SQL Editor.
-- No borra catálogos (rol, ciudad, tipo_documento, variable, etc.).
-- auth.users (Supabase Auth) NO se toca: elimine el usuario ahí si va a registrarse de nuevo.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Quitar FKs hacia usuarios (pedidos / factura pueden quedar; deben estar vacíos)
-- ---------------------------------------------------------------------------
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_fk_usuario_solicitud_fkey;
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_fk_usuario_recolector_fkey;
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_fk_usuario_repartidor_fkey;
ALTER TABLE public.factura DROP CONSTRAINT IF EXISTS factura_fk_cliente_fkey;
ALTER TABLE public.usuario_rol DROP CONSTRAINT IF EXISTS usuario_rol_id_usuario_fkey;

-- ---------------------------------------------------------------------------
-- 2) Borrar y recrear usuarios + usuario_rol
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS public.usuario_rol CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;

CREATE TABLE public.usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NOT NULL,
  nombres varchar(120) NOT NULL,
  apellidos varchar(120) NOT NULL,
  fk_tipo_documento integer NOT NULL REFERENCES public.tipo_documento (id_tipo_documento),
  documento varchar(32) NOT NULL,
  correo varchar(254) NOT NULL,
  telefono varchar(32) NOT NULL,
  capacidad_max_pedidos integer,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuarios_correo_unique UNIQUE (correo),
  CONSTRAINT usuarios_auth_user_id_unique UNIQUE (auth_user_id)
);

CREATE TABLE public.usuario_rol (
  id_usuario integer NOT NULL REFERENCES public.usuarios (id_usuario) ON DELETE CASCADE,
  id_rol integer NOT NULL REFERENCES public.rol (id_rol) ON DELETE CASCADE,
  PRIMARY KEY (id_usuario, id_rol)
);

-- ---------------------------------------------------------------------------
-- 3) Alinear columnas de pedidos (si quedaron en uuid por esquema viejo)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'pedidos'
      AND column_name = 'fk_usuario_solicitud' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.pedidos DROP COLUMN fk_usuario_solicitud;
    ALTER TABLE public.pedidos DROP COLUMN IF EXISTS fk_usuario_recolector;
    ALTER TABLE public.pedidos DROP COLUMN IF EXISTS fk_usuario_repartidor;
    ALTER TABLE public.pedidos
      ADD COLUMN fk_usuario_solicitud integer NOT NULL,
      ADD COLUMN fk_usuario_recolector integer,
      ADD COLUMN fk_usuario_repartidor integer;
  END IF;
END $$;

-- Quitar columnas huérfanas de migración 003 fallida (si existen)
ALTER TABLE public.pedidos DROP COLUMN IF EXISTS fk_usuario_solicitud_new;
ALTER TABLE public.pedidos DROP COLUMN IF EXISTS fk_usuario_recolector_new;
ALTER TABLE public.pedidos DROP COLUMN IF EXISTS fk_usuario_repartidor_new;
ALTER TABLE public.usuarios DROP COLUMN IF EXISTS id_usuario_new;

-- ---------------------------------------------------------------------------
-- 4) Recrear FKs de pedidos y factura (idempotente: DROP IF EXISTS + ADD)
-- ---------------------------------------------------------------------------
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_fk_usuario_solicitud_fkey;
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_fk_usuario_recolector_fkey;
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_fk_usuario_repartidor_fkey;

ALTER TABLE public.pedidos
  ADD CONSTRAINT pedidos_fk_usuario_solicitud_fkey
  FOREIGN KEY (fk_usuario_solicitud) REFERENCES public.usuarios (id_usuario);

ALTER TABLE public.pedidos
  ADD CONSTRAINT pedidos_fk_usuario_recolector_fkey
  FOREIGN KEY (fk_usuario_recolector) REFERENCES public.usuarios (id_usuario);

ALTER TABLE public.pedidos
  ADD CONSTRAINT pedidos_fk_usuario_repartidor_fkey
  FOREIGN KEY (fk_usuario_repartidor) REFERENCES public.usuarios (id_usuario);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'factura') THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'factura'
        AND column_name = 'fk_cliente' AND data_type = 'uuid'
    ) THEN
      ALTER TABLE public.factura DROP CONSTRAINT IF EXISTS factura_fk_cliente_fkey;
      ALTER TABLE public.factura DROP COLUMN fk_cliente;
      ALTER TABLE public.factura ADD COLUMN fk_cliente integer NOT NULL;
    END IF;
    ALTER TABLE public.factura DROP COLUMN IF EXISTS fk_cliente_new;
    ALTER TABLE public.factura DROP CONSTRAINT IF EXISTS factura_fk_cliente_fkey;
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_cliente_fkey
      FOREIGN KEY (fk_cliente) REFERENCES public.usuarios (id_usuario);
  END IF;
END $$;

COMMIT;

-- Verificar:
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'usuarios'
-- ORDER BY ordinal_position;
