/** Claves de `public.variable` (seed `database/15-seed-variables.sql`). */
export const VAR = {
  CRON_ASIGNAR_REPARTIDORES_ENABLED: 'CRON_ASIGNAR_REPARTIDORES_ENABLED',
  /** 20:00 diario: normales con entrega al día siguiente, agrupados por zona_bogota. */
  CRON_ASIGNAR_NORMAL_20H_ENABLED: 'CRON_ASIGNAR_NORMAL_20H_ENABLED',
  /** Cada 20 min: express + normales pendientes del día a repartidores libres. */
  CRON_ASIGNAR_EXPRESS_20MIN_ENABLED: 'CRON_ASIGNAR_EXPRESS_20MIN_ENABLED',
  ASIGNACION_TIPO_PEDIDO_NORMAL_ID: 'ASIGNACION_TIPO_PEDIDO_NORMAL_ID',
  ASIGNACION_TIPO_PEDIDO_EXPRESS_ID: 'ASIGNACION_TIPO_PEDIDO_EXPRESS_ID',
  ASIGNACION_MAX_ENTREGAS_POR_REPARTIDOR_DIA: 'ASIGNACION_MAX_ENTREGAS_POR_REPARTIDOR_DIA',
  ASIGNACION_ROL_REPARTIDOR_ID: 'ASIGNACION_ROL_REPARTIDOR_ID',
  ASIGNACION_ROL_SUPERVISOR_ID: 'ASIGNACION_ROL_SUPERVISOR_ID',
  /** Estados visibles en GET /supervisor/pedidos/en-reparto (lista separada por comas). */
  SUPERVISOR_PEDIDOS_EN_REPARTO_ESTADOS: 'SUPERVISOR_PEDIDOS_EN_REPARTO_ESTADOS',
  PEDIDO_ESTADO_INICIAL_ID: 'PEDIDO_ESTADO_INICIAL_ID',
  ASIGNACION_ESTADO_PEDIDO_ASIGNADO_ID: 'ASIGNACION_ESTADO_PEDIDO_ASIGNADO_ID',
  ASIGNACION_ESTADOS_PEDIDO_ELEGIBLES: 'ASIGNACION_ESTADOS_PEDIDO_ELEGIBLES',
  /** Pedido “cerrado” para el repartidor ese día (entregado, cancelado, no entregado). */
  ASIGNACION_ESTADOS_TERMINALES_REPARTIDOR: 'ASIGNACION_ESTADOS_TERMINALES_REPARTIDOR',
  REPARTIDOR_PEDIDO_ESTADO_ASIGNADO_ID: 'REPARTIDOR_PEDIDO_ESTADO_ASIGNADO_ID',
  REPARTIDOR_PEDIDO_ESTADO_RECIBIDO_ID: 'REPARTIDOR_PEDIDO_ESTADO_RECIBIDO_ID',
  /** Estado En curso (4); requerido para confirmar entrega. */
  REPARTIDOR_PEDIDO_ESTADO_EN_CAMINO_ID: 'REPARTIDOR_PEDIDO_ESTADO_EN_CAMINO_ID',
  REPARTIDOR_PEDIDO_ESTADO_ENTREGADO_ID: 'REPARTIDOR_PEDIDO_ESTADO_ENTREGADO_ID',
  REPARTIDOR_PEDIDO_ESTADO_NO_ENTREGADO_ID: 'REPARTIDOR_PEDIDO_ESTADO_NO_ENTREGADO_ID',
  ASIGNACION_GEOCODING_NOMINATIM: 'ASIGNACION_GEOCODING_NOMINATIM',
  ASIGNACION_NOMINATIM_CONTACT_EMAIL: 'ASIGNACION_NOMINATIM_CONTACT_EMAIL',
  ASIGNACION_REPARTIDORES_HUBS: 'ASIGNACION_REPARTIDORES_HUBS',
  LIST_PEDIDOS_FECHA_TZ: 'LIST_PEDIDOS_FECHA_TZ',
  REGISTER_EMAIL_AUTO_CONFIRM: 'REGISTER_EMAIL_AUTO_CONFIRM',
  /** Peso máximo por paquete (kg); valor en variable acotado entre 25 y 30. */
  PAQUETE_PESO_MAX_KG: 'PAQUETE_PESO_MAX_KG',
  PAQUETE_ALTO_MAX_CM: 'PAQUETE_ALTO_MAX_CM',
  PAQUETE_ANCHO_MAX_CM: 'PAQUETE_ANCHO_MAX_CM',
  PAQUETE_LARGO_MAX_CM: 'PAQUETE_LARGO_MAX_CM',
  /** Suma alto+ancho+largo; 0 = no validar suma. */
  PAQUETE_SUMA_LADOS_MAX_CM: 'PAQUETE_SUMA_LADOS_MAX_CM',
  PAQUETE_DIMENSIONES_OBLIGATORIAS: 'PAQUETE_DIMENSIONES_OBLIGATORIAS',
  TARIFA_BOGOTA_COP: 'TARIFA_BOGOTA_COP',
  TARIFA_FUERA_BOGOTA_COP: 'TARIFA_FUERA_BOGOTA_COP',
  TARIFA_EXPRESS_MIN_COP: 'TARIFA_EXPRESS_MIN_COP',
  TARIFA_EXPRESS_MAX_COP: 'TARIFA_EXPRESS_MAX_COP',
  TARIFA_PESO_BASE_KG: 'TARIFA_PESO_BASE_KG',
  TARIFA_RECARGO_POR_KG_COP: 'TARIFA_RECARGO_POR_KG_COP',
  TARIFA_SUMA_LADOS_BASE_CM: 'TARIFA_SUMA_LADOS_BASE_CM',
  TARIFA_RECARGO_POR_CM_SUMA_COP: 'TARIFA_RECARGO_POR_CM_SUMA_COP',
  FINANZAS_LIQUIDACION_FRECUENCIA_DEFAULT_DIAS: 'FINANZAS_LIQUIDACION_FRECUENCIA_DEFAULT_DIAS',
  /** COP pagados al repartidor por cada entrega exitosa (estado Entregado). */
  FINANZAS_TARIFA_PAGO_REPARTIDOR_ENTREGA: 'FINANZAS_TARIFA_PAGO_REPARTIDOR_ENTREGA',
  /** Nómina fija mensual (supervisión/admin); se prorratea por días del periodo KPI. */
  FINANZAS_PAGO_PERSONAL_FIJO_MENSUAL: 'FINANZAS_PAGO_PERSONAL_FIJO_MENSUAL',
  /** Meta de entregas diarias (KPI dashboard Pago a Repartidores). */
  FINANZAS_META_ENTREGAS_DIARIA: 'FINANZAS_META_ENTREGAS_DIARIA',
} as const;

export type VariableKey = (typeof VAR)[keyof typeof VAR];
